### ISSUE TITLE
[WARNING] Attempt to create a file for type 'package.to.MyEditor_field_Context' multiple times when running tests

### ISSUE THREAD

**Issue by niloc132** [gwtproject/gwt-editor#10]
Actual warning can be seen by running the gwt-editor-processor project tests:
```
[INFO] --- maven-compiler-plugin:3.6.1:testCompile (default-testCompile) @ gwt-editor-processor ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 21 source files to /home/colin/workspace/gwt-editor-apt/gwt-editor-processor/target/test-classes
[INFO] GWT-Editor-Processor (version: HEAD-SNAPSHOT) started ...
[WARNING] Attempt to create a file for type 'org.gwtproject.editor.client.impl.DelegateMapTest_1PersonEditorWithCoAddressEditorView_address_Context' multiple times
[WARNING] Exception: type >>org.gwtproject.editor.client.impl.DelegateMapTest.PersonEditorWithCoAddressEditorView << - trying to write: >>org.gwtproject.editor.client.impl.DelegateMapTest_1PersonEditorWithCoAddressEditorView_address_Context<< -> message >>Attempt to recreate a file for type org.gwtproject.editor.client.impl.DelegateMapTest_1PersonEditorWithCoAddressEditorView_address_Context<< multiple times
[WARNING] Attempt to create a file for type 'org.gwtproject.editor.client.SimpleBeanEditorTest_1PersonEditorWithAliasedSubEditors__Context' multiple times
[WARNING] Exception: type >>org.gwtproject.editor.client.SimpleBeanEditorTest.PersonEditorWithAliasedSubEditors << - trying to write: >>org.gwtproject.editor.client.SimpleBeanEditorTest_1PersonEditorWithAliasedSubEditors__Context<< -> message >>Attempt to recreate a file for type org.gwtproject.editor.client.SimpleBeanEditorTest_1PersonEditorWithAliasedSubEditors__Context<< multiple times
[WARNING] Attempt to create a file for type 'org.gwtproject.editor.client.SimpleBeanEditorTest_1PersonEditorWithCoAddressEditorView_address_Context' multiple times
[WARNING] Exception: type >>org.gwtproject.editor.client.SimpleBeanEditorTest.PersonEditorWithCoAddressEditorView << - trying to write: >>org.gwtproject.editor.client.SimpleBeanEditorTest_1PersonEditorWithCoAddressEditorView_address_Context<< -> message >>Attempt to recreate a file for type org.gwtproject.editor.client.SimpleBeanEditorTest_1PersonEditorWithCoAddressEditorView_address_Context<< multiple times
[WARNING] Attempt to create a file for type 'org.gwtproject.editor.client.SimpleBeanEditorTest_1PersonEditorWithMultipleBindings_address_Context' multiple times
[WARNING] Exception: type >>org.gwtproject.editor.client.SimpleBeanEditorTest.PersonEditorWithMultipleBindings << - trying to write: >>org.gwtproject.editor.client.SimpleBeanEditorTest_1PersonEditorWithMultipleBindings_address_Context<< -> message >>Attempt to recreate a file for type org.gwtproject.editor.client.SimpleBeanEditorTest_1PersonEditorWithMultipleBindings_address_Context<< multiple times
```

**Comment by FrankHossfeld** [comment]
Wired ... Thought, I already fixed this. 

Will take a look.

**Comment by FrankHossfeld** [comment]
Please, can you run mvn clean before mvn test and check if the message will come again?
Thanks

**Comment by FrankHossfeld** [comment]
Looks like I added something to handle `Delegates` but missed `Context`

**Comment by niloc132** [comment]
Thanks for looking into this - I'm not concerned about it for an RC release, but probably we should wrap these up for the final.

**Comment by FrankHossfeld** [comment]
I'll had some time to take another look ...

The first warning:
`[WARNING] Attempt to create a file for type 'org.gwtproject.editor.client.impl.DelegateMapTest_1PersonEditorWithCoAddressEditorView_address_Context' multiple times`
is created by the compiler. the secon one:
`[WARNING] Exception: type >>org.gwtproject.editor.client.impl.DelegateMapTest.PersonEditorWithCoAddressEditorView << - trying to write: >>org.gwtproject.editor.client.impl.DelegateMapTest_1PersonEditorWithCoAddressEditorView_address_Context<< -> message >>Attempt to recreate a file for type org.gwtproject.editor.client.impl.DelegateMapTest_1PersonEditorWithCoAddressEditorView_address_Context<< multiple times` is created by the processor and we are able to remove.

So, we are able to remove one of the two message. 

As we moved the generator to a processor, we did not change the way how he processor works compared to the generator. But, there is a huge difference. A generator is able to recognize if a source class is already generated and can stop generation:

```
    String packageName = toGenerate.getPackage().getName();
    String simpleSourceName = toGenerate.getName().replace('.', '_') + "Impl";
    PrintWriter pw = context.tryCreate(logger, packageName, simpleSourceName);
    if (pw == null) {
      return packageName + "." + simpleSourceName;
    }
```

In case the source is already generate, the `PrintWriter` is null and the generator will stop generating. 

**This does not work using a processor!**

I think we need to make the processor smarter and store the names and package of the already generated source and check, if the file is already generated and in case it is, stop writing it.

@niloc1321 What do you think?
